# Generated by Django 5.2.1 on 2025-05-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectiveSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя или ФИО потенциального спикера', max_length=150, verbose_name='Имя')),
                ('contact_info', models.CharField(blank=True, help_text='Email, ссылка на профиль, или другой способ связи', max_length=255, null=True, verbose_name='Контактная информация')),
                ('notes', models.TextField(blank=True, help_text='Любая дополнительная информация, предложенные темы, комментарии организатора', null=True, verbose_name='Заметки / Темы выступлений')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в резерв')),
                ('user_tg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospective_speaker_profile', to='bot_logic.usertg', verbose_name='Telegram пользователь (если известен)')),
            ],
            options={
                'verbose_name': 'потенциальный спикер',
                'verbose_name_plural': 'потенциальные спикеры',
                'ordering': ['-date_added'],
            },
        ),
    ]
