# Generated by Django 5.2.1 on 2025-05-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertg',
            name='is_speaker',
            field=models.BooleanField(default=False, verbose_name='Спикер'),
        ),
    ]
