# Generated by Django 5.2.1 on 2025-05-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0002_usertg_is_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='stack',
        ),
    ]
