# Generated by Django 5.2.1 on 2025-05-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0003_remove_client_stack_remove_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='address',
        ),
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
        migrations.RemoveField(
            model_name='session',
            name='finish_session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_session',
        ),
    ]
