# Generated by Django 5.2.1 on 2025-05-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0004_remove_session_address_remove_session_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakersession',
            name='topic',
        ),
    ]
