# Generated by Django 5.2.1 on 2025-05-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0005_remove_speakersession_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bot_logic.event', verbose_name='мероприятие'),
        ),
    ]
