# Generated by Django 5.2.1 on 2025-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0006_session_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakersession',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Закончил ли выступление'),
        ),
    ]
