# Generated by Django 5.2.1 on 2025-05-25 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0007_speakersession_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bot_logic.event'),
        ),
    ]
