# Generated by Django 5.2.1 on 2025-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0008_question_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
