# Generated by Django 5.2.1 on 2025-05-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0009_client_biography_alter_speaker_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
    ]
