# Generated by Django 5.2.1 on 2025-05-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0010_client_is_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='bot_logic.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='bot_logic.event')),
            ],
            options={
                'verbose_name': 'регистрация на мероприятие',
                'verbose_name_plural': 'регистрации на мероприятия',
                'unique_together': {('client', 'event')},
            },
        ),
    ]
